[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Enable multi-version compilation support
auto_detect_solc = true

[invariant]
run = 50
debt = 10
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
